### ISSUE TITLE
EL9/CentOS9 Basic Support

### ISSUE THREAD

**Issue by Vonng** [Vonng/pigsty#111]
Add support for CentOS 9

**Comment by alemacci** [comment]
I can help on this.
Since CentOS goes Stream (upstream/development branch of RHEL), I think it is possible to evaluate the use of Rocky Linux as CentOS replacement.

**Comment by Vonng** [comment]
It's a great idea to use a template repo file instead of repo_upstreams. Saves lots of config space.

HAProxy rpm used by pigsty are built with https://github.com/Vonng/haproxy-rpm.

Which enables built-in Prometheus metrics support. Maybe I can compile an El8/EL9 version and upgrade to v2.6

**Comment by alemacci** [comment]
Another step forward.

I am testing OL8 also, which is working well.

Another issue is when we use '**yum install --downloadonly**' cmd for downloading repo packages on **_./roles/repo/tasks/main.yml_**, il will not download packages that have already been installed on control node.

I think we can rely on repotrack command, which will do both jobs and works well on newest EL builds (on EL8/9 it became an alias of 'dnf download' command).

While specifing '--arch x86_64,noarch' switch, i686 packages can be excluded. This behavior doesn't work on EL7 due to https://bugzilla.redhat.com/show_bug.cgi?id=1150115 (but code can be patched https://getridbug.com/unix-linux/download-all-dependencies-with-yumdownloader-even-if-already-installed/)

```
    # download packages from upstream yum repo
    - name: Download repo packages and their dependencies
      tags: repo_pkg
      environment: "{{ proxy_env }}"
      command:
        cmd: repotrack --arch x86_64,noarch {{ item }}
        chdir: "{{ nginx_home }}/{{ repo_name }}"
      with_items: "{{ repo_packages }}"
```
