### ISSUE TITLE
Fix incompatible parameters when upgrading to Loki 2.5.0

### ISSUE THREAD

**Issue by Vonng** [Vonng/pigsty#115]
Changes on `/etc/loki.yml`

```yaml
limits_config:
  split_queries_by_interval: 30m

analytics:
  reporting_enabled: false
```
