### ISSUE TITLE
Add PostgreSQL 15 Beta Support

### ISSUE THREAD

**Issue by Vonng** [Vonng/pigsty#132]
Create a pg15 beta config for testing purposes.

Disable PostGIS / Timescale / Citus and other extensions (since they are not ready in PG15)

```yaml
    repo_packages:                    # which packages to be included                                                    
      - postgresql15*

    pg_packages:                      # postgresql related packages. `${pg_version} will be replaced by `pg_version`
      - postgresql${pg_version}*      # postgresql kernel packages
      # - postgis32_${pg_version}*      # postgis
      # - citus_${pg_version}*          # citus
      # - timescaledb-2-postgresql-${pg_version}    # timescaledb
      - pgbouncer pg_exporter pgbadger pg_activity node_exporter consul haproxy vip-manager
      - patroni patroni-consul patroni-etcd python3 python3-psycopg2 python36-requests python3-etcd
      - python3-consul python36-urllib3 python36-idna python36-pyOpenSSL python36-cryptography
    pg_extensions: [ ]                # postgresql extensions, `${pg_version} will be replaced by actual `pg_version`
    # - pg_repack_${pg_version} pg_qualstats_${pg_version} pg_stat_kcache_${pg_version} pg_stat_monitor_${pg_version} wal2json_${pg_version}
    # - ogr_fdw${pg_version} mysql_fdw_${pg_version} redis_fdw_${pg_version} mongo_fdw${pg_version} hdfs_fdw_${pg_version}
    # - count_distinct${version}  ddlx_${version}  geoip${version}  orafce${version}
    # - hypopg_${version}  ip4r${version}  jsquery_${version}  logerrors_${version}  periods_${version}  pg_auto_failover_${version}  pg_catcheck${version}
    # - pg_fkpart${version}  pg_jobmon${version}  pg_partman${version}  pg_prioritize_${version}  pg_track_settings${version}  pgaudit15_${version}
    # - pgcryptokey${version}  pgexportdoc${version}  pgimportdoc${version}  pgmemcache-${version}  pgmp${version}  pgq-${version}  pgquarrel pgrouting_${version}
    # - pguint${version}  pguri${version}  prefix${version}   safeupdate_${version}  semver${version}   table_version${version}  tdigest${version}


```
