### ISSUE TITLE
when I setup with<Singleton Meta>

### ISSUE THREAD

**Issue by orangeyts** [Vonng/pigsty#149]
everything is ok ,but what postgres db default username and password,I want to login db

**Comment by Vonng** [comment]
In your config file
You can use default admin user by default

dbuser_dba
DBUser.DBA
meta

冯若航（Ruohang Feng）

在 2022年7月27日，15:00，Jerry ***@***.***> 写道：

﻿

everything is ok ,but what postgres db default username and password,I want to login db

**Comment by orangeyts** [comment]
is need modify pg_hba.conf ?  still have below error message when use client to connect,  it looks like some whilelist want to be add

The specified database user/password combination is rejected: [28000] FATAL: no pg_hba.conf entry for host "125.70.169.250", user "dbuser_dba", database "meta", no encryption

**Comment by Vonng** [comment]
The default hba allow primary meta node user access by default.



```yaml
pg_hba_rules:                     # postgres host-based authentication rules
  # TODO: allow all meta nodes password access
  - title: allow meta node password access
    role: common
    rules:
      - host    all     all                         10.10.10.10/32      md5
```

The placeholder will be replaced with your meta node ip. You can initial connection from there with default admin superuser:

```bash
postgres://dbuser_dba:DBUser.DBA@<ip>:5432/meta
```

Or just use another biz user defined in `pg_users`, for example:

```yaml
postgres://dbuser_meta:DBUser.Meta@<ip>:5432/meta
```

**Comment by orangeyts** [comment]
default config(/data/postgres/pg-meta-14/data/pg_hba.conf) can not connect,  add ISP public IP is ok, 
and **_select pg_reload_conf();_** 
 client can connected.
`
#==============================================================#
# Common HBA
#==============================================================#
#  allow meta node password access
host    all     all                         172.18.133.74/32      md5
host    all     all                         公网IP: 125.70.169.250/32     trust
`

**Comment by kaka-ruto** [comment]
If anyone finds themselves here, I had to allow any host access the db with the username and password by adding this to the configuration and running `./install.yml` to rebuild everything. I didn't find a way to reload the database configuration without rebuilding. Do we have one?

```yml
pg_hba_rules: 
  - title: allow meta node password access
    role: common
    rules:
      - host    all     all                         0.0.0.0/0      md5
```
