### ISSUE TITLE
部署监控的时候报错

### ISSUE THREAD

**Issue by mawenbin666** [Vonng/pigsty#156]
1、配置信息如下：
```
    test-db-pg-aimp-s-1.1:
      hosts:
        192.168..1.1: { pg_seq: 1, pg_role: primary }
      vars:
        pg_cluster: pg-dp
        pg_users: [ { name: dbuser_monitor , password: xxx, pgbouncer: true , roles: [ dbrole_admin ] , comment: test user } ]
        pg_databases: [ { name: dp , extensions: [ { name: postgis, schema: public } ] } ]
```
2、启动报错
[root]# ./pgsql-monly.yml -l pg-dp
[WARNING]: Could not match supplied host pattern, ignoring: pg-dp
ERROR! Specified hosts and/or --limit does not match any hosts
