### ISSUE TITLE
使用精简监控模式的疑问

### ISSUE THREAD

**Issue by darkz1984** [Vonng/pigsty#167]
参考文档:
https://pigsty.cc/zh/docs/deploy/monitor/#%E7%9B%91%E6%8E%A7%E5%B7%B2%E6%9C%89%E5%AE%9E%E4%BE%8B%E7%B2%BE%E7%AE%80%E6%A8%A1%E5%BC%8F

修改配置为文件  pigsty.yml 增加pg集群:
```
    pg-50:
      hosts:                                # 为每个实例分配唯一本地端口
        192.168.112.50: { pg_seq: 1, pg_role: primary , pg_exporter_port: 20001}
      vars:
        pg_cluster: pg-50                 # 填入集群名称
        pg_version: 11.13                 # 填入数据库大版本
        pg_databases: [{ name: dianxin }, {name: dh}] # 填入数据库列表（每个数据库对象作为一个数组元素）

        pg_port: 5433                                 # postgres port, 5432 by default
        pg_monitor_username: dbuser_monitor           # system monitor user
        pg_monitor_password: DBUser.Monitor           # system monitor password
```

实际发现没有看到pg-50 pg实例相关的监控数据
