### ISSUE TITLE
Pigsty 2.0 API Planning

### ISSUE THREAD

**Issue by Vonng** [Vonng/pigsty#177]
Modularized API Design, Split `etcd` from `infra`:

Single node example:

```yaml
all:
  vars: # global params that override role's default

    # admin node ip address, ca, ansible & yum repos
    admin_ip: 10.10.10.10  # reconfig with real addr
    version: v2.0.0-a1  # pigsty version string info
    region: default   # values: default|china|europe

  children: # cluster definitions and group override

    # infra cluster for proxy, monitor, alert, etc..
    infra: { hosts: { 10.10.10.10: { infra_seq: 1 } } }

    # etcd cluster for postgres/patroni ha consensus
    etcd: { hosts: { 10.10.10.10: { etcd_seq: 1 } } }

    # minio cluster for s3 compatible object storage
    minio: { hosts: { 10.10.10.10: { minio_seq: 1 } } , vars: { minio_cluster: minio } }

    # pgsql: primary|replica|standby|offline|delayed
    pgsql: { hosts: { 10.10.10.10: { pg_seq: 1, pg_role: primary } }, vars: { pg_cluster: pg-meta } }

    # redis mode: standalone|sentinel|cluster(native)
    redis: { hosts: { 10.10.10.10: { redis_node: 1, redis_instances: { 6379: { } } } }, vars: { redis_cluster: redis-meta } }
```

3 infra nodes & a 3-node etcd cluster example:

```yaml
all:
  vars: # global params that override role's default

    # admin node IP address, ca, ansible & yum repos
    admin_ip: 10.10.10.10  # reconfig with real addr
    version: v2.0.0-a1  # pigsty version string info
    region: default   # values: default|china|europe

  children: # cluster definitions and group override

    infra: # infra cluster for proxy, monitor, alert, etc
      hosts: # 1 for common usage, 3 nodes for production
        10.10.10.10: { infra_seq: 1 } # identity required
        10.10.10.11: { infra_seq: 2 } # assign from 1 ~ n
        10.10.10.12: { infra_seq: 3 } # DO NOT reuse seqs
    
    etcd: # dcs service for postgres/patroni ha consensus
      hosts: # 1 for testing, 3 or 5 for production usage
        10.10.10.10: { etcd_seq: 1 }  # etcd_seq required
        10.10.10.11: { etcd_seq: 2 }  # assign from 1 ~ n
        10.10.10.12: { etcd_seq: 3 }  # DO NOT reuse seqs
      vars: # cluster level parameter override roles/etcd
        etcd_cluster: etcd  # mark etcd cluster name etcd
        etcd_safeguard: false # safeguard against purging
        etcd_clean: true # purge etcd during init process
    
    minio: # minio cluster for logs, backups, images, etc
      hosts: # 1 for demo, 3 or more for production usage
        10.10.10.13: { minio_seq: 1 } # identity required
        10.10.10.14: { minio_seq: 2 } # assign from 1 ~ n
        10.10.10.15: { minio_seq: 3 } # DO NOT reuse seqs
      vars:
        minio_cluster: minio-main
        minio_access_key: minioadmin
        minio_secret_key: minioadmin
        minio_address: ":9091"
```
