### ISSUE TITLE
HBA Rules API

### ISSUE THREAD

**Issue by Vonng** [Vonng/pigsty#189]
We already have `hba` parameters such as `pg_hba_rules` and etc...

Which are array of `hba` object, each `hba` object may look like

```yaml
- title: allow intranet password access
  role: common
  rules:
    - host   all  all  10.0.0.0/8      md5
    - host   all  all  172.16.0.0/12   md5
    - host   all  all  192.168.0.0/16  md5
```

We can extend `hba` object with an alternative DSL:

```yaml
- addr: 'intra'    # world|intra|infra|admin|local|localhost|<cidr>
  auth: 'pwd'      # trust|pwd|ssl|cert|deny|<official auth method>
  user: 'all'      # all|${dbsu}|${repl}|${admin}|${monitor}|<user>|<group>
  db: 'all'        # all|replication|....
  rules: []        # raw hba string precedance over above all
  title: allow intranet password access
```

For professional user, you can use `rules` to define your raw hba rules.

Or use this alternative way to define your hba rules.

The benifit is that now user have more control over security policy with a more simple approach.

Some examples of rewrite current hba rules:

```yaml

pg_hba:

  - title: dbsu local ident access
    subject: ${dbsu}
    scope: local
    method: ident
    #rules:
    #  - local   all          postgres  ident

  - title: dbsu local ident replication access
    subject: ${dbsu}
    scope: local
    database: replication
    method: ident
    #rules:
    #  - local   replication  postgres  ident

  - title: replicator localhost pwd replication access
    subject: ${repl}
    scope: localhost
    database: replication
    #rules:
    #  - local replication  replicator                md5
    #  - host  replication  replicator  127.0.0.1/32  md5

  - title: replicator intranet pwd ssl postgres db access
    subject: ${repl}
    scope: intra
    database: replication
    method: ssl
    #rules:
    #  - hostssl replication  replicator  10.0.0.0/8     md5
    #  - hostssl replication  replicator  172.16.0.0/12  md5
    #  - hostssl replication  replicator  192.168.0.0/16 md5

  - title: replicator intranet pwd replication access
    subject: ${repl}
    scope: intra
    database: replication
    method: ssl
    #rules:
    #  - hostssl replication  replicator  10.0.0.0/8     md5
    #  - hostssl replication  replicator  172.16.0.0/12  md5
    #  - hostssl replication  replicator  192.168.0.0/16 md5

  - title: admin world clientcert ssl access (public internet)
    subject: ${admin}
    scope: world
    method: cert
    #rules:
    #  - hostssl replication  replicator all clientcert verify-full

  - title: admin intranet password ssl access
    subject: ${admin}
    scope: intra
    method: ssl
    #rules:
    #  - hostssl dbuser_dba 10.0.0.0/8     md5
    #  - hostssl dbuser_dba 172.16.0.0/12  md5
    #  - hostssl dbuser_dba 192.168.0.0/16 md5

  - title: monitor localhost password access
    subject: ${monitor}
    scope: localhost
    #rules:
    #  - local replication  dbuser_monitor                md5
    #  - host  replication  dbuser_monitor  127.0.0.1/32  md5

  # FOR GRAFANA DATASOURCE
  - title: monitor infra nodes password ssl access
    subject: ${monitor}
    scope: infra
    #rules:
    #  - hostssl  replication  dbuser_monitor  10.10.10.10/32  md5
    #  - hostssl  replication  dbuser_monitor  10.10.10.11/32  md5 ...

  # BUSINESS PRODUCTION USER via local pgbouncer
  - title: read/write localhost password access
    role: default
    subject: +dbrole_readonly
    scope: localhost
    #rules:
    #  - local     all     +dbrole_readonly                  md5
    #  - host      all     +dbrole_readonly  127.0.0.1/32    md5
  
  # YOU CAN LIMIT OFFLINE ACCESS TO CERTAIN BASTION/SPRINGBOARD/BIGDATA HOSTS
  - title: intranet offline queries (etl,saga,interactive)
    role: offline
    subject: +dbrole_offline
    scope: intra  # <bastion_ip> | <bigdata_cidr>
    #rules:
    #  - host      all     +dbrole_offline   10.0.0.0/8      md5
    #  - host      all     +dbrole_offline   172.16.0.0/12   md5
    #  - host      all     +dbrole_offline   192.168.0.0/16  md5

```

Example of default hba rules:

```yaml
- {title: dbsu local ident access,                        subject: ${dbsu},          scope: local,     method: ident },
- {title: dbsu local ident replication access,            subject: ${dbsu},          scope: local,     method: ident, database: replication},
- {title: replicator localhost pwd replication access,    subject: ${repl},          scope: localhost,                database: replication}
- {title: replicator intranet pwd ssl postgres db access, subject: ${repl},          scope: intra,                    database: postgres   },
- {title: replicator intranet pwd replication access,     subject: ${repl},          scope: intra,                    database: replication},
- {title: admin world client cert ssl access,             subject: ${admin},         scope: world,     method: cert },
- {title: admin intranet password ssl access,             subject: ${admin},         scope: intra,     method: ssl  },
- {title: monitor localhost password access,              subject: ${monitor},       scope: localhost },
- {title: monitor infra nodes password ssl access,        subject: ${monitor},       scope: infra     },
- {title: read/write localhost password access,           subject: +dbrole_readonly, scope: localhost },
- {title: intranet offline queries (etl,saga),            subject: +dbrole_offline,  scope: intra,     role: offline },
- {title: everyone intranet password access,              subject: all,              scope: intra,     role: common  }
```

Example of default hba rules for security enhanced mode:

```yaml
- {title: dbsu local ident access,                        subject: ${dbsu},          scope: local,     method: ident  },
- {title: dbsu local ident replication access,            subject: ${dbsu},          scope: local,     method: ident,   database: replication},
- {title: replicator localhost pwd replication access,    subject: ${repl},          scope: localhost, method: sha256,  database: replication}
- {title: replicator intranet pwd ssl postgres db access, subject: ${repl},          scope: intra,     method: ssl-sha, database: postgres   },
- {title: replicator intranet pwd replication access,     subject: ${repl},          scope: intra,     method: ssl-sha, database: replication},
- {title: admin infra nodes client cert ssl access,       subject: ${admin},         scope: intra,     method: cert   },
- {title: reject admin world access,                      subject: ${admin},         scope: world,     method: reject },
- {title: monitor localhost password access,              subject: ${monitor},       scope: localhost, method: sha256 },
- {title: monitor infra nodes password cert ssl access,   subject: ${monitor},       scope: infra,     method: cert   },
- {title: reject monitor world access,                    subject: ${monitor},       scope: world,     method: reject },
- {title: read/write localhost password access,           subject: +dbrole_readonly, scope: localhost, method: sha256 },
- {title: intranet offline queries (etl,saga),            subject: +dbrole_offline,  scope: 10.1.0.0/16,role: offline },
```
  
* DO NOT GRANT everyone intranet password access  
* require client cert for admin & monitor user
* reject unnecessary admin & monitor access from world
* mandatory ssl for replication, clients, `verify-full` always
* use scram-sha-256 explicitly, which reject md5 password encryption
