### ISSUE TITLE
Export services in node port style with haproxy

### ISSUE THREAD

**Issue by Vonng** [Vonng/pigsty#191]
We can move haproxy to `node` instead of `pgsql`.

Then it can be used as a generic load balancer for various services such as etcd / minio / redis / prometheus / grafana ... , The user can also use several global lb instead of pgsql ad hoc haproxy instances.

We can move role `haproxy` to `node.yml`, reuse node identity as haproxy identity. 
Adding a new variable `services` to expose them, for example:

```
haproxy_services:                 # list of haproxy service
  - name: pg-test-ro              # [REQUIRED] service name, unique
    src_port: 5440                # [REQUIRED] service port, unique
    src_ip: "*"                   # [OPTIONAL] service listen addr, "*" by default
    protocol: tcp                 # [OPTIONAL] service protocol, 'tcp' by default
    balance: leastconn            # [OPTIONAL] load balance algorithm, roundrobin by default (or leastconn)
    maxconn: 20000                # [OPTIONAL] max allowed front-end connection, 20000 by default
    default_server: 'inter 3s fastinter 1s downinter 5s rise 3 fall 3 on-marked-down shutdown-sessions slowstart 30s maxconn 3000 maxqueue 128 weight 100'
    options:
      - option httpchk
      - option http-keep-alive
      - http-check send meth OPTIONS uri /read-only
      - http-check expect status 200
    servers:
      - { name: pg-test-1 ,ip: 10.10.10.11 , port: 5432 , options: check port 8008 , backup: true }
      - { name: pg-test-2 ,ip: 10.10.10.12 , port: 5432 , options: check port 8008 }
      - { name: pg-test-3 ,ip: 10.10.10.13 , port: 5432 , options: check port 8008 }

  - name: redis-test              # [REQUIRED] service name, unique
    src_port: 5441                # [REQUIRED] service port, unique
    src_ip: "*"                   # [OPTIONAL] service listen addr, "*" by default
    protocol: tcp                 # [OPTIONAL] service protocol, 'tcp' by default
    balance: roundrobin           # [OPTIONAL] load balance algorithm, roundrobin by default (or leastconn)
    maxconn: 20000                # [OPTIONAL] max allowed front-end connection, 20000 by default
    default_server: 'inter 3s fastinter 1s downinter 5s rise 3 fall 3 on-marked-down shutdown-sessions slowstart 30s maxconn 3000 maxqueue 128 weight 100'
    servers:
      - { name: redis-test-1-6501 , ip: 10.10.10.11 , port: 6501 , options: check }
      - { name: redis-test-1-6502 , ip: 10.10.10.11 , port: 6502 , options: check }
      - { name: redis-test-1-6503 , ip: 10.10.10.11 , port: 6503 , options: check }
      - { name: redis-test-2-6501 , ip: 10.10.10.12 , port: 6501 , options: check }
      - { name: redis-test-2-6502 , ip: 10.10.10.12 , port: 6502 , options: check }
      - { name: redis-test-2-6503 , ip: 10.10.10.12 , port: 6503 , options: check }
```

and existing `pg_services` and `pg_services` extra can be compile to that format in `pg_register` role.

Which can also be simplified as:

```yaml
pg_default_services:              # expose postgres service with local node haproxy
  - { name: '${pg_cluster}-primary' ,src: 5433 ,dst: auto     ,check: /primary   ,selector: "[]" }
  - { name: '${pg_cluster}-replica' ,src: 5434 ,dst: auto     ,check: /read-only ,selector: "[]" , backup: "[? pg_role == `primary` || pg_role == `offline` ]" }
  - { name: '${pg_cluster}-standby' ,src: 5435 ,dst: auto     ,check: /sync      ,selector: "[]" }
  - { name: '${pg_cluster}-default' ,src: 5436 ,dst: postgres ,check: /primary   ,selector: "[]" }
  - { name: '${pg_cluster}-offline' ,src: 5438 ,dst: postgres ,check: /replica   ,selector: "[? pg_role == `offline` || pg_offline_query ]" , backup: "[? pg_role == `replica` && !pg_offline_query]"}

```
