### ISSUE TITLE
Scrape patroni metrics with SSL

### ISSUE THREAD

**Issue by Vonng** [Vonng/pigsty#195]
if `patroni_ssl_enabled` , we have to scrape patroni endpoint (8008) with `https` schema and `tls_config` in prometheus.

But we want to keep it simple by bookkeep pg/pgb/patroni in same target file `/etc/prometheus/targets/pgsql/{{ pg_instance }}.yml` rather than 3 files.

Looking into a solution for that.

**Comment by Vonng** [comment]
There are several options:

1. use a separate target definition for Patroni: 
  e.g. `/etc/prometheus/targets/pgsql/{{ pg_instance }}.patroni.yml`
  define another scrape job and overwrite job lable
  really ugly, but can work, looking for a better solution, otherwise fall back to this

2. use https for pg_exporter by default
  we may enforce SSL for all pg related exporters

**Comment by alemacci** [comment]
Hmmm....

I think we're good as long we are using `verify_client: optional` 

Since retreiving /metrics is a GET request (safe), setting verify_client to optional will protect form unsafe calls only (PUT, POST, PATCH and DELETE)

Ref: https://patroni.readthedocs.io/en/latest/security.html?highlight=verify_client#protecting-the-rest-api

**Comment by Vonng** [comment]
The problem is about monitor target book keeping:

```yaml
#------------------------------------------------------------------------------
# job: pgsql
# node_exporter pg_exporter | pgbouncer_exporter | patroni
# labels: [cls, ins, ip, instance]
# path: targets/pgsql/<pg_instance>.yml
#------------------------------------------------------------------------------
- job_name: pgsql
  metrics_path: {{ exporter_metrics_path }}
  file_sd_configs:
    - refresh_interval: {{ prometheus_sd_interval }}
      files: [ targets/pgsql/*.yml ]
```

```bash
$ cat targets/pgsql/pg-meta-1.yml
# pg-meta-1 [primary] @ 10.10.10.10
- labels: { cls: pg-meta, ins: pg-meta-1, ip: 10.10.10.10 }
  targets:
    - 10.10.10.10:9630
    - 10.10.10.10:9631
    - 10.10.10.10:8008
```


We can do that in another approach

```yaml
#------------------------------------------------------------------------------
# job: pgsql-patroni
# labels: [cls, ins, ip, instance, job]
# path: targets/patroni/<pg_instance>.yml
#------------------------------------------------------------------------------
- job_name: pgsql-patroni
  metrics_path: /metrics     # patroni metrics path is not customizable
  honor_labels: true
  scheme: https
  tls_config:
    ca_file: /etc/pki/ca.crt
    cert_file: /etc/pki/infra.crt
    key_file: /etc/pki/infra.key
  file_sd_configs:
    - refresh_interval: {{ prometheus_sd_interval }}
      files: [ targets/patroni/*.yml ]
```

```yaml
# pg-meta-1 [primary] @ 10.10.10.10
- labels: { cls: pg-meta, ins: pg-meta-1, ip: 10.10.10.10 ,job: pgsql}
  targets: [ 10.10.10.10:8008 ]
```

Looking for a way to override Prometheus scrape config scheme, or get metrics withiout https.
