### ISSUE TITLE
Add script `pg-add` & `pg-rm` to add/remove pgsql instance

### ISSUE THREAD

**Issue by Vonng** [Vonng/pigsty#198]
If we want to add a pgsql instance to existing cluster, 

e.g, add `10.10.10.13` to `pg-test` 

```
pg-test:                          # define the new 3-node cluster pg-test
  hosts:
    10.10.10.11: { pg_seq: 1, pg_role: primary }   # primary instance, leader of cluster
    10.10.10.12: { pg_seq: 2, pg_role: replica }   # replica instance, follower of leader
    10.10.10.13: { pg_seq: 3, pg_role: replica, pg_offline_query: true } # NEWLY ADDED
  vars:
    pg_cluster: pg-test           # define pgsql cluster name
    pg_users:  [{ name: test , password: test , pgbouncer: true , roles: [ dbrole_admin ] }]
    pg_databases: [{ name: test }] # create a database and user named 'test'
    pg_vip_enabled: true
    pg_vip_address: 10.10.10.3/24
    pg_vip_interface: eth1
```

the official procedure were:

```
./pgsql.yml -l 10.10.10.13   # init that 
bin/pg-svc pg-test           # refresh cluster service definition, required
bin/pg-hba pg-test           # refresh cluster postgres hba rules, optional?
bin/pgb-hba pg-test          # refresh cluster pgbouncer hba rules, optional?
```

What if we simplify that with one wrapper command:

```bash
bin/pg-add <cluster>               # one parameter, init that cluster
bin/pg-add <cluster> <ins|seq|ip>  # two parameter, add ins to cluster 
```

Where the first form would just be like `./pgsql.yml -l <cluster>`

and the second would be :

```
./pgsql.yml -l <ins>                        # init that ins
./pgsql.yml -t pg_hba -e pg_reload=true     # reload cluster postgres hba  
./pgsql.yml -t pgbouncer_hba,pgbouncer_reload -e pg_reload=true # reload cluster pgbouncer hba
./pgsql.yml -t pg_service -e haproxy_reload=true                # refresh cluster services
```

The `pgsql-rm` script would be more tricky.

If we have to refresh pgsql cluster without that removed instance, we can use ansible's `add_host` dynamic inventory functionaility.
