### ISSUE TITLE
update pgsql-migration.yml to generate migration plan base on logical replication

### ISSUE THREAD

**Issue by Vonng** [Vonng/pigsty#222]
We can add a feature to migrate from existing outside postgres:

Here is a migration task with necessary information:

src & dst cluster name, primary ip address and database name.

```yaml
---
#-----------------------------------------------------------------
# PG_MIGRATION
#-----------------------------------------------------------------
context_dir: ~/migration           # migration manuals & scripts
#-----------------------------------------------------------------
# SRC Cluster (The OLD Cluster)
#-----------------------------------------------------------------
src_cls: pg-meta      # src cluster name         <REQUIRED>
src_db: meta          # src database name        <REQUIRED>
src_ip: 10.10.10.10   # src cluster primary ip   <REQUIRED>
#src_pg: ''            # if defined, use this as src dbsu pgurl instead of:
#                      # postgres://{{ pg_admin_username }}@{{ src_ip }}/{{ src_db }}
#                      # e.g. 'postgres://dbuser_dba:DBUser.DBA@10.10.10.10:5432/meta'
#sub_conn: ''          # if defined, use this as subscription connstr instead of:
#                      # host={{ src_ip }} dbname={{ src_db }} user={{ pg_replication_username }}'
#                      # e.g. 'host=10.10.10.10 dbname=meta user=replicator password=DBUser.Replicator'
#-----------------------------------------------------------------
# DST Cluster (The New Cluster)
#-----------------------------------------------------------------
dst_cls: pg-test      # dst cluster name         <REQUIRED>
dst_db: test          # dst database name        <REQUIRED>
dst_ip: 10.10.10.11   # dst cluster primary ip   <REQUIRED>
#dst_pg: ''            # if defined, use this as dst dbsu pgurl instead of:
#                      # postgres://{{ pg_admin_username }}@{{ dst_ip }}/{{ dst_db }}
#                      # e.g. 'postgres://dbuser_dba:DBUser.DBA@10.10.10.11:5432/test'
#-----------------------------------------------------------------
# PGSQL
#-----------------------------------------------------------------
pg_dbsu: postgres
pg_replication_username: replicator
pg_replication_password: DBUser.Replicator
pg_admin_username: dbuser_dba
pg_admin_password: DBUser.DBA
pg_monitor_username: dbuser_monitor
pg_monitor_password: DBUser.Monitor
#-----------------------------------------------------------------
...
```

And we can create a migration plan with the following playbook:

```bash
./pgsql-migration.yml  @files/migration/pg-meta.yml
```

Which will generate a migration manual & scripts on the admin user

```
ls ~/migration/<src_cls>.<src_db>

- activate       # migration context
- check-user     # check src users
- check-db       # check src databases
- check-hba      # check src hba rules
- check-repl     # check src replica identities
- check-misc     # check src special objects
- copy-schema    # copy schema from src to dst
- copy-seq       # copy sequences from src to dst
- copy-progress  # print logical replication initial sync complete ratio
- copy-diff      # diff src/dst table count to check logical replication is synced
- create-pub     # create publication on src
- drop-pub       # drop publication on src
- create-sub     # create subscription on dst
- drop-sub       # drop subscription on dst
```

All we have to do is follow the generated manual README.md
