### ISSUE TITLE
Add `pg_default_service_dest` to switch between postgres & pgbouncer

### ISSUE THREAD

**Issue by Vonng** [Vonng/pigsty#225]
The default `primary` & `replica` services are routed to pgbouncer 6432 port by default.

We can change that behavior by adding a new parameter, `pg_default_service_dest`

And we can allow a new enum in `svc.dest`:  `postgres|pgbouncer|default`. If the value is default,
Then it will use `pg_default_service_dest` instead.

```yaml
pg_default_service_dest: pgbouncer # default service destination port when svc.dest = 'default'
pg_default_services:              # postgres default service definitions
- { name: primary ,port: 5433 ,dest: default   ,check: /primary   ,selector: "[]" }
- { name: replica ,port: 5434 ,dest: default   ,check: /read-only ,selector: "[]" , backup: "[? pg_role == `primary` || pg_role == `offline` ]" }
- { name: default ,port: 5436 ,dest: postgres  ,check: /primary   ,selector: "[]" }
- { name: offline ,port: 5438 ,dest: postgres  ,check: /replica   ,selector: "[? pg_role == `offline` || pg_offline_query ]" , backup: "[? pg_role == `replica` && !pg_offline_query]"}
```
