### ISSUE TITLE
New config template `dual.yml` for two node deployment

### ISSUE THREAD

**Issue by Vonng** [Vonng/pigsty#248]
It is recommended to use at least three nodes in production deployment.
But sometimes, there are only two nodes available. So we can provide a `files/pigsty/dual.yml` config template for this scenario.

In this setup, we have two nodes, `.10` (admin_node) and `.11` (pgsql_priamry):

* If `.11` is down, `.10` will take over since the dcs:etcd is still alive
* If `.10` is down, `.11` (pgsql primary) will still be functioning as a primary if:
  * Only dcs:etcd is down
  * Only pgsql is down
  * if both etcd & pgsql are down (e.g. node down), the primary will still demote itself.  

```yaml
all:
  children:

    infra:
      hosts:
        10.10.10.10: { infra_seq: 1 } # identity required
        10.10.10.11: { infra_seq: 2, repo_enabled: false }

    # etcd cluster for ha postgres
    etcd: { hosts: { 10.10.10.10: { etcd_seq: 1 } }, vars: { etcd_cluster: etcd } }

    # minio cluster, optional backup repo for pgbackrest
    #minio: { hosts: { 10.10.10.10: { minio_seq: 1 } }, vars: { minio_cluster: minio } }

    pg-meta:      # 3 instance postgres cluster `pg-meta`
      hosts:
        10.10.10.10: { pg_seq: 1, pg_role: replica }
        10.10.10.11: { pg_seq: 2, pg_role: primary } # <--- use this as default primary
      vars:
        pg_cluster: pg-meta
        pg_vip_enabled: true
        pg_vip_address: 10.10.10.2/24
        pg_vip_interface: eth1
```
