### ISSUE TITLE
[Feature Request]  Also import id_ed25519 keys 

### ISSUE THREAD

**Issue by cocoonkid** [Vonng/pigsty#260]
```
    - name: add current user public key
      tags: node_admin_pk_current
      when: node_admin_pk_current|bool
      authorized_key:
        user: "{{ node_admin_username }}"
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
...
```

.ssh/id_ed25519.pub

Or actually should be added to VARS
