### ISSUE TITLE
Prometheus permission error.

### ISSUE THREAD

**Issue by cocoonkid** [Vonng/pigsty#273]
I am getting this on multiple fresh  Rocky9 systems.

The requested file is not created.  Or cannot be created. 

roles/infra/tasks/prometheus.yml 
looks okay but there is apparently an issue ?

`  msg="Error opening query log file" file=/data/prometheus/data/queries.active err="open /data/prometheus/data/queries.active: permission denied"`

![image](https://user-images.githubusercontent.com/43231640/231896683-9d10ce6c-c2a2-4ca5-b9fd-db539e58508f.png)

The task for creating the directories looks good too.

![image](https://user-images.githubusercontent.com/43231640/231898246-1e451cd7-2236-413b-bc12-5a2f0287cb82.png)

**Comment by cocoonkid** [comment]
I was able to fix it for now with 
`chmod -R 777 /data/` 
but this is just a hack.

**Comment by Vonng** [comment]
The `/data` dir is owned by root with 777 by default. specified by [`node_data`]

Maybe we can separated the chmod part from mkdir ?


```yaml
#--------------------------------------------------------------#
# Stage 3: Create data dir if not exists             [node_data]
#--------------------------------------------------------------#
# TODO: MOUNT DISK TO DATA DIR NOW LEAVES TO USER
- name: assure node data dir exists
  tags: node_data
  when: node_data is defined and node_data != '' and node_data != '/'
  shell: >-
    mkdir -p "{{ node_data }}" -m 777;
    chown root:root "{{ node_data }}"
    /bin/true
```

**Comment by cocoonkid** [comment]
In my case the permissions had already been set by the zfs pool when creating it via ansible. (I fixed that there now.) 
So when the dir already exists it seems mkdir does not fix the perms.

I suppose to add a task that verfies the permissions.



```
#--------------------------------------------------------------#
# Stage 3: Create data dir if not exists             [node_data]
#--------------------------------------------------------------#
# TODO: MOUNT DISK TO DATA DIR NOW LEAVES TO USER
- name: Assure node data dir exists
  tags: node_data
  when: node_data is defined and node_data != '' and node_data != '/'
  ansible.builtin.file:
    path: "{{ node_data }}"
    state: directory
    owner: root
    group: root

- name: Set node data dir permissions
  tags: node_data
  when: node_data is defined and node_data != '' and node_data != '/'
  ansible.builtin.file:
    path: "{{ node_data }}"
    mode: '0777'
```
