### ISSUE TITLE
After upgrade to 2.4.1 we are getting postgres 15.4

### ISSUE THREAD

**Issue by resulraveendran** [Vonng/pigsty#327]
Hi,
    After upgrading to 2.4.1 we are getting Postgres 15.4, Why is not upgrading to version 16. Are there any changes we want to make for this?

**Comment by Vonng** [comment]
Yeah the default `pg_version` is still 15, because some important extensions are still not ready for PG 16 yet.

Usually we will bump the **DEFAULT** `pg_version` after:
- [ ] the second minor release of PG 16 (16.1)
- [ ] `pg_repack_16` and `wal2json` is ready for EL8/EL9
- [ ] `citus_16`, and `timescaledb_16` is ready for EL8/EL9

But you can still install PG 16 with explicit version number (pg_version: 16) without some extensions.

- [`prod.yml`](https://github.com/Vonng/pigsty/blob/master/files/pigsty/prod.yml#L176)
- [`check.yml`](https://github.com/Vonng/pigsty/blob/master/files/pigsty/check.yml#L371)

```yaml
    pg-v16: # PostgreSQL 16 is not available on el7
      hosts: { 10.10.10.16: { pg_seq: 1 ,pg_role: primary } }
      vars:
        pg_cluster: pg-v16
        pg_version: 16
        pg_libs: 'pg_stat_statements, auto_explain'
        pg_packages: [ postgresql16* pgbouncer pg_exporter pgbadger vip-manager patroni patroni-etcd pgbackrest ]
        pg_extensions: [ ]
        pg_users: [ { name: test , password: test , pgbouncer: true , roles: [ dbrole_admin ] } ]
        pg_databases: [ { name: v16 } ]

```

Available extensions for PG 16 can be found in

- [`build.yml.repo_packages`](https://github.com/Vonng/pigsty/blob/master/files/pigsty/build.yml#L134)
- [PGDG-16 Repo](https://download.postgresql.org/pub/repos/yum/16/redhat/rhel-8-x86_64/)
