### ISSUE TITLE
Refector `node-id`, `configure`, `bootstrap` to fit different OS Distributions

### ISSUE THREAD

**Issue by Vonng** [Vonng/pigsty#328]
If we want to support Ubuntu 22.04 & 20.04 & Debian 12 : 

Ubuntu Support: https://github.com/Vonng/pigsty/issues/53

Debian Support: https://github.com/Vonng/pigsty/issues/293

The first thing to do is adjust the way we get distribution information

We should fetch vendor & version from `/etc/os-release` rather than `/etc/redhat-release`

Besides, this will resolve the [Anolis](https://github.com/Vonng/pigsty/issues/325) compatability issue, too.

```yaml
    # gather node fact, also check connectivity
    - name: get node fact
      become: no
      shell: |
        . /etc/os-release > /dev/null
        echo $ID
        echo $VERSION_ID
        echo $(uname -m);
        echo $(whoami)
        echo $(hostname);
        echo $(grep -c '^processor' /proc/cpuinfo);
        echo $(getconf _PHYS_PAGES);
        echo $(getconf PAGE_SIZE);
        /bin/true;
      register: node_result

    # calculate node identity
    - name: set node fact
      connection: local
      set_fact:
        os_vendor:      "{{ node_result.stdout_lines[0] }}"
        os_version:     "{{ node_result.stdout_lines[1]|int }}"
        os_arch:        "{{ node_result.stdout_lines[2] }}"
        node_user:      "{{ node_result.stdout_lines[3] }}"
        node_hostname:  "{{ node_result.stdout_lines[4] }}"
        node_cpu:       "{{ node_result.stdout_lines[5]|int }}"
        node_pages:     "{{ node_result.stdout_lines[6]|int }}"
        node_page_size: "{{ node_result.stdout_lines[7]|int }}"
```
