### ISSUE TITLE
New docker application template: Odoo

### ISSUE THREAD

**Issue by Vonng** [Vonng/pigsty#383]
[Odoo](https://www.odoo.com/) is a powerful ERP system based on PostgreSQL. It would be great to add to the docker templates without much effort.

We can add this to the demo site too, like odoo.pigsty

```yaml
services:
  odoo:
    container_name: odoo
    image: odoo:17.0
    ports:
      - "${ODOO_PORT}:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      #- ${ODOO_DATA}:/var/lib/odoo
      #- ./config:/etc/odoo
    environment:
      - HOST=${PG_HOST}
      - PORT=${PG_PORT}
      - USER=${PG_USER}
      - PASSWORD=${PG_PASS}
```
