### ISSUE TITLE
New parameters to control node etc hosts

### ISSUE THREAD

**Issue by Vonng** [Vonng/pigsty#385]
Docker VMs does not allow writing to `/etc/hosts`

We should have a new parameter (maybe `node_write_hosts`) to control that behavior.

**Comment by Vonng** [comment]
Adding a new parameter: `node_write_etc_hosts`

```yaml
#--------------------------------------------------------------#
# Setup Node Static DNS Records                     [node_hosts]
#--------------------------------------------------------------#
- name: setup node dns
  tags: node_hosts
  when: node_write_etc_hosts|bool
```

Besides, if `dns_enabled` is false, the pgsql role should not write dns records

to infra nodes' /etc/hosts
