### ISSUE TITLE
Use os-independt extension name in additional to os package in `pg_extensions`

### ISSUE THREAD

**Issue by Vonng** [Vonng/pigsty#434]
We want to use:

```yaml
pg_extensions:
  - postgis timescaledb vector wal2json pg_repack
```

Rather than os-specific package names such as:

**`deb`**:

```yaml
- postgresql-$v-repack postgresql-$v-wal2json
- postgresql-$v-postgis* timescaledb-2-postgresql-$v postgresql-$v-pgvector
```

**`rpm`**:

```yaml
- pg_repack_$v* wal2json_$v* passwordcheck_cracklib_$v*                        # important extensions
- postgis34_$v* timescaledb-2-postgresql-$v* pgvector_$v*                      # featured extensions installed by default
```

To address this, we will need an extension map for that.

```yaml
pg_extension_map:                 # internal data: translate pg_extension to os package
  rpm:
    postgis:     postgis34_$v*
    timescaledb: timescaledb-2-postgresql-$v*
    vector:      pgvector_$v*
    wal2json:    wal2json_$v*
    pg_repack:   pg_repack_$v*
  deb:
    postgis:     postgresql-$v-postgis*
    timescaledb: timescaledb-2-postgresql-$v
    vector:      postgresql-$v-pgvector
    wal2json:    postgresql-$v-wal2json
    pg_repack:   postgresql-16-repack
```
