### ISSUE TITLE
Adaptive pg_tune template

### ISSUE THREAD

**Issue by Vonng** [Vonng/pigsty#80]
A postgres/patroni configuration parameters can be determined by some basic facts:

* cpu core number
* memory size
* disk size
* disk type (ssd|hdd|san) 
* max connection
* purpose: oltp, olap, crit , tiny(demo) 

Thus there is no need to hard code cpu & mem spec in patroni configuration

```yaml
# max connection for postgres
max_connections: {{ pg_maxconn }}

shared_preload_libraries: '{{ pg_shared_libraries }}'

# enable 2pc if citus enabled
{% if 'citus' in pg_shared_libraries %}
max_prepared_transactions: {{ pg_maxconn }}             # 0 disable 2PC
{% else %}
max_prepared_transactions: 0            # 0 disable 2PC
{% endif %}


// < 8GB = 64
// >=8GB, < 16GB = 128
// >=16GB, < 32GB = 256
// >=32GB = 512
max_locks_per_transactions: 64

# set worker process to cpu core
{% if cpu_core_number >= 2 %}
max_worker_processes: {{ cpu_core_number }}
max_parallel_workers: {{ cpu_core_number }}
max_parallel_workers_per_gather: {{ cpu_core_number }} or max(4)
max_parallel_maintenance_workers: {{ cpu_core_number / 2 }}  or max(4)
{% else %}
max_worker_processes: 2
max_parallel_workers: 2
max_parallel_workers_per_gather = 1
max_parallel_maintenance_workers = 1
{% endif %}

# for production env, set to 32, otherwise default
{% if pg_tune != 'tiny' %}
max_wal_senders: 32
max_replication_slots: 32
{% endfi %}


# 2GB for tiny, dozens of GB for prod
min_wal_size: 2GB

# at most 40% disk space
max_wal_size: 8GB

# perhaps 10% - 20% disk space
temp_file_limit: 20GB                   # 0 -> 40GB (according to your disk)

# 1/4 mem as shared buffer (max 32 GB for crit|oltp)
shared_buffers: {{ availab_mem|4 }} or min(64MB) or max(32GB)
effective_cache_size: {{ availab_mem - shared_buffers }}

# decide maintain work mem
work_mem:  {{ share_buffer / max_connection }} | min(64kb) | max(64MB)
maintenance_work_mem: {{ share_buffer / max_parallel_maintenance_workers }} | max(2047MB)

default_statistics_target: 100
random_page_cost: 1.1
checkpoint_completion_target: 0.9
```

**Comment by alemacci** [comment]
I can help on this

**Comment by Vonng** [comment]
Thanks a lot~.

beware of a corner case where the replica has a different node spec than the primary instance (e.g lower mem/cpu spec). The auto-generated conf needs to take care of this case.

Since inconsist conf may lead to failure of starting new replicas.

```yaml
max_connections: 100                    # default 100
superuser_reserved_connections: 10      # reserve 10 connection for su
max_locks_per_transaction: 64           # default 64
max_prepared_transactions: 0            # 0 disable 2PC
track_commit_timestamp: on              # enabled xact timestamp
max_worker_processes: 8                 # keep default 8 (set to cpu core)
wal_level: logical                      # logical
wal_log_hints: on                       # wal log hints to support rewind
# max_wal_senders: 24                   # 10 -> 24
# max_replication_slots: 16             # 10 -> 16
wal_keep_size: 1GB                      # keep at least 1GB WAL
password_encryption: md5                # use traditional md5 auth
```

Some tuning templates & resources

https://pgtune.leopard.in.ua/

https://github.com/timescale/timescaledb-tune/tree/main/pkg/pgtune
